version: '3'
services:
  frontend:
    build: 
      context: ./frontend            # Location of the frontend Dockerfile
      dockerfile: Dockerfile         # Name of the frontend Dockerfile
    ports:
      - "3000:3000"                  # Expose port 3000 for the frontend
    depends_on:
      - backend                      # Ensure backend service is running before starting frontend

  backend:
    build:
      context: ./backend             # Location of the backend Dockerfile
      dockerfile: Dockerfile         # Name of the backend Dockerfile
    ports:
      - "5000:5000"                  # Expose port 5000 for the backend
